{
 "title": "e-Mikutano Overview",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "panels": [
  { "title": "e-Mikutano monitoring metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 1 },
   "options": {
    "content": "<div class=\"col-12  px-0\">\n\t\t<div class=\"col-md-10 offset-md-1 col-xs-12 col-sm-12 mb-2 mt-0 top-middle\">\n\t\t  <div class=\"row px-xs-2\">\n\t\t\t\t<div class=\"col-md-2 col-sm-2 col-xs-2 float-left text-left pt-1\">\n\t\t\t\t\t<a href=\"#\"><img src=\"https://www.ega.go.tz/site/images/emblem.png\" alt=\"emblem\" class=\"mx-auto img-fluid emblem\"></a>\n\t\t\t\t</div>\n\n\t\t\t\t<div class=\"col-md-8 col-sm-8 col-xs-8 text-center pt-3 pt-xs-0\">\n\t\t\t\t\t<h1 class=\"mb-0 title title-main\"> <br> Jamhuri ya Muungano wa Tanzania</h1>\n\t\t\t\t\t<h4 class=\"title-desc\"><b><i>Mfumo wa Mawasiliano kwa Njia ya Video</i></b></h4>\n\t\t\t\t</div>\n\n\t\t\t\t<div class=\"col-md-2 col-sm-2 col-xs-2 text-right client-logo pt-1 pr-0\"><img src=\"https://www.ega.go.tz/site/images/logo.png\" alt=\"eGA Logo\" class=\"img-fluid\"></div>\n\t\t\t\t</div>\n\t\t </div>\n\t</div>"
   },
   "targets": [
    {}
   ]
  },
  { "title": "Current Values", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Online Clients (e-Mikutano)",
   "type": "stat",
   "description": "Number of participants currently in meetings",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mikutano_stats",
     "query": "SELECT last(\"participants\") FROM \"mikutano_stats\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "participants" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Running Conferences (e-Mikutano)",
   "type": "stat",
   "description": "Number of conferences being held",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mikutano_stats",
     "query": "SELECT last(\"participants\") FROM \"mikutano_stats\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "conferences" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "(Not complete)Number of reserved conferences (e-Maombi) ",
   "type": "stat",
   "description": "Total number of reserved conferences to date",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mikutano_stats",
     "query": "SELECT last(\"participants\") FROM \"mikutano_stats\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "participants" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Videobridge RX",
   "type": "stat",
   "description": "total bytes sent by the video-bridge",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "Kbits" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mikutano_stats",
     "select": [
      [
       { "params": [ "bit_rate_download" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Videobridge RX",
   "type": "stat",
   "description": "total bytes sent by the video-bridge",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "Kbits" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mikutano_stats",
     "select": [
      [
       { "params": [ "bit_rate_download" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Maombi TX (not compete)",
   "type": "stat",
   "description": "total bytes sent by the video-bridge",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "Kbits" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mikutano_stats",
     "select": [
      [
       { "params": [ "bit_rate_download" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Maombi RX (not compete)",
   "type": "stat",
   "description": "total bytes sent by the video-bridge",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "Kbits" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mikutano_stats",
     "select": [
      [
       { "params": [ "bit_rate_download" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Network Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Network Transmission",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "KBs" } },
   "yaxes": [
    { "format": "KBs" }
   ],
   "targets": [
    {
     "alias": "bit rate download",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mikutano_stats",
     "select": [
      [
       { "params": [ "bit_rate_download" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "bit rate upload",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mikutano_stats",
     "select": [
      [
       { "params": [ "bit_rate_upload" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "*-1" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Ping Response Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "KBs" } },
   "yaxes": [
    { "format": "KBs" }
   ],
   "targets": [
    {
     "alias": "bit rate download2",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ping",
     "select": [
      [
       { "params": [ "average_response_ms" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "mikutano-main-vm" }
     ]
    },
    {
     "alias": "bit rate download",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ping",
     "select": [
      [
       { "params": [ "average_response_ms" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "mikutano-main-vm" }
     ]
    }
   ]
  },
  { "title": "System metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "MY-SQL (I/O) (transactions per second) (not complete)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "alias": "reads",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "diskio",
     "query": "SELECT derivative(mean(\"read_bytes\"), 10s) AS \"read\", derivative(mean(\"write_bytes\"), 10s) AS \"write\" FROM \"diskio\" WHERE $timeFilter GROUP BY time(1m) fill(null)",
     "select": [
      [
       { "params": [ "reads" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "*-1" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "mikutano-main-vm" }
     ]
    },
    {
     "alias": "writes",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "diskio",
     "query": "SELECT derivative(mean(\"read_bytes\"), 10s) AS \"read\", derivative(mean(\"write_bytes\"), 10s) AS \"write\" FROM \"diskio\" WHERE $timeFilter GROUP BY time(1m) fill(null)",
     "select": [
      [
       { "params": [ "writes" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "mikutano-main-vm" }
     ]
    }
   ]
  },
  {
   "title": "CPU Usage (e-Mikutano)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "$col",
     "measurement": "cpu",
     "select": [
      [
       { "params": [ "usage_guest" ], "type": "field" }
      ],
      [
       { "params": [ "usage_idle" ], "type": "field" }
      ],
      [
       { "params": [ "usage_iowait" ], "type": "field" }
      ],
      [
       { "params": [ "usage_irq" ], "type": "field" }
      ],
      [
       { "params": [ "usage_nice" ], "type": "field" }
      ],
      [
       { "params": [ "usage_softirq" ], "type": "field" }
      ],
      [
       { "params": [ "usage_steal" ], "type": "field" }
      ],
      [
       { "params": [ "usage_system" ], "type": "field" }
      ],
      [
       { "params": [ "usage_user" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "mikutano-main-vm" },
      { "condition": "AND", "key": "cpu", "operator": "=", "value": "cpu-total" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "user" ], "type": "tag" }
     ],
     "measurement": "procstat",
     "select": [
      [
       { "params": [ "num_threads" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "mikutano-main-vm" }
     ]
    }
   ]
  },
  {
   "title": "CPU Usage (e-Maombi) (Not Completed)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "$col",
     "measurement": "cpu",
     "select": [
      [
       { "params": [ "usage_guest" ], "type": "field" }
      ],
      [
       { "params": [ "usage_idle" ], "type": "field" }
      ],
      [
       { "params": [ "usage_iowait" ], "type": "field" }
      ],
      [
       { "params": [ "usage_irq" ], "type": "field" }
      ],
      [
       { "params": [ "usage_nice" ], "type": "field" }
      ],
      [
       { "params": [ "usage_softirq" ], "type": "field" }
      ],
      [
       { "params": [ "usage_steal" ], "type": "field" }
      ],
      [
       { "params": [ "usage_system" ], "type": "field" }
      ],
      [
       { "params": [ "usage_user" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "mikutano-main-vm" },
      { "condition": "AND", "key": "cpu", "operator": "=", "value": "cpu-total" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "user" ], "type": "tag" }
     ],
     "measurement": "procstat",
     "select": [
      [
       { "params": [ "num_threads" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "mikutano-main-vm" }
     ]
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "description": "Memory usage in percentage used",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "Mikutano $col",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "mem",
     "select": [
      [
       { "params": [ "available_percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Avaliable" ], "type": "alias" }
      ],
      [
       { "params": [ "used_percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Used" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "mikutano-main-vm" }
     ]
    },
    {
     "alias": "Maombi $col",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "mem",
     "select": [
      [
       { "params": [ "used_percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Used" ], "type": "alias" }
      ],
      [
       { "params": [ "available_percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Avaliable" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "mikutano-main-vm" }
     ]
    }
   ]
  },
  {
   "title": "Threads",
   "type": "graph",
   "description": "Number of threads spawned by users",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "user" ], "type": "tag" }
     ],
     "measurement": "procstat",
     "select": [
      [
       { "params": [ "num_threads" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "mikutano-main-vm" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "user" ], "type": "tag" }
     ],
     "measurement": "procstat",
     "select": [
      [
       { "params": [ "num_threads" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "mikutano-main-vm" }
     ]
    }
   ]
  }
 ]
}